language: rust
sudo: false
rust: stable
cache: cargo
env:
  global:
  - CARGO_VENDOR_VERSION=0.1.23
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-musl
    # TODO
    #- env: TARGET=aarch64-unknown-linux-musl
    #  sudo: required
    #- env: TARGET=armv7-unknown-linux-musleabihf
    #  addons:
    #    apt:
    #      packages:
    #        - gcc-arm-linux-gnueabihf
install:
- curl -sSfL https://github.com/alexcrichton/cargo-vendor/releases/download/${CARGO_VENDOR_VERSION}/cargo-vendor-${CARGO_VENDOR_VERSION}-x86_64-unknown-linux-musl.tar.gz
  | tar xzf - -C $HOME/bin --strip-components=1
- cargo vendor --version
- rustup target add $TARGET
script:
- if [[ $TARGET == "aarch64-unknown-linux-musl" ]]; then sudo apt-get install -y --force-yes --no-install-recommends gcc-aarch64-linux-gnu libc6-arm64-cross libc6-dev-arm64-cross; fi
- cargo build --release --target $TARGET --locked
- strip target/$TARGET/release/nix-user-chroot
notifications:
  email:
    on_success: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: m6wa43gSK2bkqwjrFlDseoTFz91UuebQuo9kdrmzpAHsiPeBjf/R1g06WzCUiy+YOGOHic6/pMUrI/TlywNCCJP5S/RDsBBqmEAzzPurOUCCQDg21rBM3zb2voZKWQf0TtTHAAhizRCRGkDvuOUMXRTn9OuNd5J8FjpSLA/v/QT+o3UhTYgbSCmMZrKzyZim80hqRuJynjWFT7P0PoG7Nk8fj5lnEay27Lot2loL2cPuVJXrbA670K6py2xOiwfQPLxZ7oW+lDiLqJZ/BhfHn35SzMmY/e21vWXBpM4mWiVa7Oq/ArnppKMnB4G63gkNaH13qpd3NRWGxDoEtnt6c9tvFIywZXbewmQ5RQYDmQmwttMDG+IOZS4RTOyKf9TxvctLgwavT0kodW6z/Y+2p52wqaBrehz+bVU/R5iq9j869NrDAyPMi5hRcqnmSHKvAvmPETsALb06NX0Dko/ZEsjmJYRnm86bf0pjpZW0YZs4hHJiITPc6A6d3pjTml6vdr9luiY+wAjN499sML9YNFJg+6xiz6k7TbwgIVhw5PVsy0x2IjGvzbVF7xSgx3dtx67JuD3kA5LUWQ/0+X2P8IIjAwYJ6yUNVLofZziZQ7gyGn5uyFGjKFftGGbmaXc9jNTIM52hlT7h0ezEnC6MMoitR4ajBoDLJBiaWs2uVL4=
  file_glob: true
  file:
    - nix-user-chroot-$TRAVIS_TAG-$TARGET.tar.gz
    - nix-user-chroot-src-$TRAVIS_TAG.tar.gz
    - nix-user-chroot-bin-$TRAVIS_TAG-$TARGET
  on:
    repo: nix-community/nix-user-chroot
    tags: true
