language: rust
sudo: false
rust: stable
cache: cargo
env:
  global:
  - CARGO_VENDOR_VERSION=0.1.23
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-musl
    # TODO
    #- env: TARGET=aarch64-unknown-linux-musl
    #  sudo: required
    #- env: TARGET=armv7-unknown-linux-musleabihf
    #  addons:
    #    apt:
    #      packages:
    #        - gcc-arm-linux-gnueabihf
install:
- curl -sSfL https://github.com/alexcrichton/cargo-vendor/releases/download/${CARGO_VENDOR_VERSION}/cargo-vendor-${CARGO_VENDOR_VERSION}-x86_64-unknown-linux-musl.tar.gz
  | tar xzf - -C $HOME/bin --strip-components=1
- cargo vendor --version
- rustup target add $TARGET
script:
- if [[ $TARGET == "aarch64-unknown-linux-musl" ]]; then sudo apt-get install -y --force-yes --no-install-recommends gcc-aarch64-linux-gnu libc6-arm64-cross libc6-dev-arm64-cross; fi
- cargo build --release --target $TARGET --locked
- strip target/$TARGET/release/nix-user-chroot
notifications:
  email:
    on_success: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "2TmIeI5kn6TetQ09q+zDV0Pd+J2yBKG5NwHBEXqLVY7GLl5rzsYOzomh0+FaGNjHa4z7jRTxkeZnFrY+fV8gqV21GU6zn8odHfGDWw8ocuIb7XOsy8Qbzk1bv9xgMassuuGhljS5E5VW98CH+ID6p7SViECwnf68nurv2MIZDXo2Ct3g3d5kr/uvlRCuFo9NHsRi1si/jERUa8IZ/mHMbEePZoW2qa5rMeo1NsmvnI/+z6NReBHWXn5q8mNnTtDpmZLYdTmDLzayGSRD/iZSsAm5VgKRrSF/D9JbwZSflDpmryqQ0TPkhx35zgLlo3wLYVIA0bZEtEBE2bKwbao4xwy/H8J3JuXRaoV7pqqJhtlnvJ8OOUKM8rQfVl+R5sD8EoXFmutdfrAxhbm6zPlXTjSUfgjUTu8gi70osKSsk5D9xVoH0WxwT6xCNtvjk16g5g+T74LGqwHyjXMWG2ZBRpUh39bvLR2r8hDWe98oax2R+mgrP7nJtQ5SclzyUKKDS3eDGfIPOmIrYJC09W8GpA5XjK83pszg5/6Mj78kJ3hlKHK2cbyzH/lzvW+JItymJWSGBzBJI2QJ1JjSdU3oMcZlx0+8CDwYOIZrjsEcjzoSBH+Nht1i1yGR4vcNTdH3HuHyAhwqyuOHEFuj4Hdmwesd3Do22GYCf8lxgUSDsR4="
  file_glob: true
  file:
    - nix-user-chroot-$TRAVIS_TAG-$TARGET.tar.gz
    - nix-user-chroot-src-$TRAVIS_TAG.tar.gz
    - nix-user-chroot-bin-$TRAVIS_TAG-$TARGET
  on:
    repo: nix-community/nix-user-chroot
    tags: true
