language: rust
sudo: false
rust: stable
cache: cargo
env:
  global:
    - CARGO_VENDOR_VERSION=0.1.23
  matrix:
    - TARGET=x86_64-unknown-linux-musl
    - TARGET=i686-unknown-linux-musl
    - TARGET=aarch64-unknown-linux-musl
    - TARGET=armv7-unknown-linux-musleabihf

install:
  - curl -sSfL https://github.com/alexcrichton/cargo-vendor/releases/download/${CARGO_VENDOR_VERSION}/cargo-vendor-${CARGO_VENDOR_VERSION}-x86_64-unknown-linux-musl.tar.gz | tar xzf - -C $HOME/bin --strip-components=1
  - cargo vendor --version
  - rustup target add $TARGET

script:
  - cargo build --release --target $TARGET --locked
  - strip target/$TARGET/release/nix-user-chroot

notifications:
  email:
    on_success: never

before_deploy:
  - name="nix-user-chroot-$TRAVIS_TAG-$TARGET"
  - depsname="nix-user-chroot-src-$TRAVIS_TAG"
  - install -D target/$TARGET/release/nix-user-chroot $name/nix-user-chroot
  - install -D target/$TARGET/release/nix-user-chroot nix-user-chroot-bin-$TRAVIS_TAG-$TARGET
  - mkdir $depsname
  - git archive HEAD | tar -x -C $depsname
  - cargo vendor
  - mv vendor $depsname/
  - tar czvf $depsname.tar.gz $depsname

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "Y6aR3PeWAWzvsndnMzgpN+ViCUNXYsMkZnIAqW3eSl7UVZcPNC75QrUn0fybVH43UE0FFSl96pmWyZ0Xs39C9YK3iBxC1tvyWHQhiC1/WK4o8x9Me6YBOOVZwIQNZnuNfN7Dx4D1jDiBmtjO61u5JmmQ5+CjCEp5jn60/wkrGoLk7Fm6/VHGbUml2P9CjdvAZ/jlJxnCdYfOc3vhFgR9o8SRECUiimwiBBPRHXlxFbl7bExcH/Ut3BnJCMekLyDnTzDAsKcHEypPpzqhkEiM9beDYPvATwUsK04FTxDCmV4/FmfemMRghPUZ4F/pRVPfpsXvAnLaAGuEo4+2Gx08reg+u8l+049LBbOC4/xgtb0fUFYT5f41gIzz4mKtcAJeipr4djSHPGqj9bigUbZbTiebVuCiSPUOQgRrMHKkBDI20seSGicApFRz/iUDlC6Rz4F2C9inOLsQRjsvfzrVNuJe2gS2cLszG39Is6N+dgaxrxjETBDicQnNSQ9xTHZPLmrcSPg4c8Th5BwW0RILb6FF8kgbmMXje0RRWYo9yzpEYc5Wd6i2k2c0B3Egc7bP4qR/d3CQrrhMfcY2J8vmNiUX+xhjmzofdIFRBvrEVzeIG8pPG0XMw28uXxv8VAuNI2/TEe+MyNGnvLjw2xpiV/bu9XDDDv0Altmhj7T7h30="
  file_glob: true
  file:
    - nix-user-chroot-$TRAVIS_TAG-$TARGET.tar.gz
    - nix-user-chroot-src-$TRAVIS_TAG.tar.gz
    - nix-user-chroot-bin-$TRAVIS_TAG-$TARGET
  on:
    repo: nix-community/nix-user-chroot
    tags: true
