[package]
name = "nix-user-chroot"
description = "Install & Run nix without root permissions"
license = "MIT"
version = "1.2.1"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"

[dependencies]
nix = "0.20.0"
libc = "0.2.93"
